name: Snake

on:
  schedule: # execute every 3 days
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  build:
    name: update commits graph
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v3
        #id: snake-gif
        with:
          github_user_name: r3drun3
          #svg_out_path: dist/github-contribution-grid-snake.svg
          outputs: |
            dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
